apiVersion: v2
name: chainflip-prometheus-exporter
version: 2.0.23
appVersion: 2.6.0
description: Scrape data from all supported chains
maintainers:
  - name: Chainflip Labs
    email: dev@chainflip.io
    url: https://chainflip.io
type: application