apiVersion: v2
name: chainflip-prometheus-exporter
version: 2.0.18
appVersion: 2.5.2
description: Scrape data from all supported chains
maintainers:
  - name: Chainflip Labs
    email: dev@chainflip.io
    url: https://chainflip.io
type: application