apiVersion: v2
name: node
description: |
  Deploy a Chainflip Validator, Archive, Broker or LP node on Kubernetes

maintainers:
  - name: Chainflip Labs GmbH
    email: dev@chainflip.io
    url: https://chainflip.io

type: application

version: 0.19.1

appVersion: "1.10.0"
