apiVersion: v2
name: node
description: |
  Deploy a Chainflip Validator or Archive node on Kubernetes

maintainers:
  - name: Chainflip Labs GmbH
    email: dev@chainflip.io
    url: https://chainflip.io

type: application

version: 0.14.0

appVersion: "1.6.4"
